// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "starwars-api",
    "version": "1"
  },
  "paths": {
    "/postNewCharacter": {
      "post": {
        "summary": "postCharacter",
        "description": "",
        "operationId": "postCharacter.post./postNewCharacter",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/getKeysInSpanish": {
      "get": {
        "summary": "getKeysInSpanish",
        "description": "",
        "operationId": "getKeysInSpanish.get./getKeysInSpanish",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/getResources": {
      "get": {
        "summary": "getResources",
        "description": "",
        "operationId": "getResources.get./getResources",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/getStoredCharacters": {
      "get": {
        "summary": "getStoredCharacters",
        "description": "",
        "operationId": "getStoredCharacters.get./getStoredCharacters",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/getTotalFilms": {
      "get": {
        "summary": "getTotalFilms",
        "description": "",
        "operationId": "getTotalFilms.get./getTotalFilms",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/getTotalSpecies": {
      "get": {
        "summary": "getTotalSpecies",
        "description": "",
        "operationId": "getTotalSpecies.get./getTotalSpecies",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/getTotalVehicles": {
      "get": {
        "summary": "getTotalVehicles",
        "description": "",
        "operationId": "getTotalVehicles.get./getTotalVehicles",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/getTotalStarships": {
      "get": {
        "summary": "getTotalStarships",
        "description": "",
        "operationId": "getTotalStarships.get./getTotalStarships",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    }
  },
  "definitions": {},
  "securityDefinitions": {}
};